#!/usr/bin/env node
// Regenerates src/protocol/tags.generated.ts from the backend tag database.
// Run manually after backend/draco_sim/tags/tags.yaml changes:
//   node scripts/gen-tags.mjs
//
// This is a tiny purpose-built parser for the flat "list of dicts with scalar
// fields" shape tags.yaml actually uses -- not a general YAML parser.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const srcPath = join(here, '..', '..', 'backend', 'draco_sim', 'tags', 'tags.yaml');
const outPath = join(here, '..', 'src', 'protocol', 'tags.generated.ts');

const text = readFileSync(srcPath, 'utf-8');
const lines = text.split(/\r?\n/);

function parseScalar(raw) {
  let v = raw.trim();
  if (v === 'null' || v === '') return null;
  if (v === 'true') return true;
  if (v === 'false') return false;
  if (/^-?\d+(\.\d+)?$/.test(v)) return Number(v);
  if (v.startsWith('"') && v.endsWith('"')) return v.slice(1, -1);
  if (v.startsWith("'") && v.endsWith("'")) return v.slice(1, -1);
  return v;
}

const rows = [];
let current = null;
for (const line of lines) {
  const tagStart = line.match(/^\s{2}- tag:\s*(.+)$/);
  if (tagStart) {
    if (current) rows.push(current);
    current = { tag: parseScalar(tagStart[1]) };
    continue;
  }
  if (!current) continue;
  const field = line.match(/^\s{4}(\w+):\s*(.*)$/);
  if (field) {
    const [, key, val] = field;
    if (val.startsWith('[') || val === '>-' || val === '|') continue; // arrays/block scalars: not needed here
    current[key] = parseScalar(val);
  }
}
if (current) rows.push(current);

const DIGITAL = 'digital_out';

/** @type {{name:string,kind:string,direction:'in'|'out',dtype:'REAL'|'BOOL',units:string,signal:string,normalState:'NO'|'NC'|null,description:string,reserved:boolean}[]} */
const tags = rows
  .filter((r) => r.kind === 'analog_in' || r.kind === 'derived' || r.kind === DIGITAL)
  .map((r) => ({
    name: r.tag,
    kind: r.kind,
    direction: r.kind === DIGITAL ? 'out' : 'in',
    dtype: r.kind === DIGITAL ? 'BOOL' : 'REAL',
    units: r.units ?? '',
    signal: r.signal ?? '',
    normalState: r.normal_state ?? null,
    description: r.description ?? '',
    reserved: Boolean(r.reserved),
  }));

if (tags.length !== 46) {
  console.warn(`warning: expected 46 tags, parsed ${tags.length} -- check tags.yaml formatting`);
}

const banner = `// GENERATED by frontend/scripts/gen-tags.mjs from backend/draco_sim/tags/tags.yaml.
// Do not hand-edit; re-run the script after the tag database changes.
`;

const body = `${banner}
export interface TagInfo {
  name: string;
  kind: string;
  direction: 'in' | 'out';
  dtype: 'REAL' | 'BOOL';
  units: string;
  signal: string;
  normalState: 'NO' | 'NC' | null;
  description: string;
  reserved: boolean;
}

export const DRACO_TAGS: TagInfo[] = ${JSON.stringify(tags, null, 2)};
`;

writeFileSync(outPath, body, 'utf-8');
console.log(`wrote ${tags.length} tags to ${outPath}`);
