// GENERATED by frontend/scripts/copy-examples.mjs from backend/examples/.
// Do not hand-edit; re-run the script after the example programs change.

import type { ProgramSource } from './types';

export const EXAMPLES: ProgramSource[] = [
  {
    "name": "abort_monitor",
    "language": "ST",
    "source": "(* Auto-abort thresholds. This program only computes the request bit: the scan loop\n   decides whether to call runtime.trigger_abort(). *)\n\nPROGRAM abort_monitor\nVAR_GLOBAL\n    (* PLACEHOLDER -- set by operator; not calibrated *)\n    pt0_abort_threshold : REAL := 0.0;    (* chamber pressure, psi *)\n    pt5_abort_threshold : REAL := 0.0;    (* LOX manifold, psi *)\n    pt15_abort_threshold : REAL := 0.0;   (* fuel engine manifold, psi *)\n\n    (* Arms the monitor. FALSE until the operator has configured the thresholds\n       above: with them at their placeholder 0.0 any positive reading requests an\n       abort, so an armed monitor safes the stand within two scans of plc.run. *)\n    abort_monitor_enable : BOOL := FALSE;\n\n    auto_abort_request : BOOL := FALSE;\nEND_VAR\n\n    IF abort_monitor_enable THEN\n        auto_abort_request := (PT0 > pt0_abort_threshold)\n                           OR (PT5 > pt5_abort_threshold)\n                           OR (PT15 > pt15_abort_threshold);\n    ELSE\n        auto_abort_request := FALSE;   (* disarmed: never leave the bit latched true *)\n    END_IF;\n\nEND_PROGRAM\n"
  },
  {
    "name": "bangbang_fuel",
    "language": "LD",
    "source": {
      "version": 1,
      "language": "LD",
      "name": "bangbang_fuel",
      "description": "Fuel tank bang-bang pressurisation in ladder form: PT13 -> S2. Same hysteresis as bangbang_lox; setpoint and deadband are operator-set at runtime (initial values recorded from the stand's last pre-fire configuration, 2026-09-11).",
      "vars": [
        {
          "name": "setpoint_fuel",
          "type": "REAL",
          "scope": "VAR_GLOBAL",
          "init": 870,
          "comment": "psi, operator-set"
        },
        {
          "name": "deadband_fuel",
          "type": "REAL",
          "scope": "VAR_GLOBAL",
          "init": 15,
          "comment": "psi, operator-set"
        },
        {
          "name": "bb_fuel_enable",
          "type": "BOOL",
          "scope": "VAR_GLOBAL",
          "init": false
        },
        {
          "name": "lo",
          "type": "REAL",
          "scope": "VAR",
          "comment": "setpoint - deadband"
        },
        {
          "name": "hi",
          "type": "REAL",
          "scope": "VAR",
          "comment": "setpoint + deadband"
        }
      ],
      "rungs": [
        {
          "id": "r1",
          "comment": "Recompute the hysteresis band every scan so operator edits take effect",
          "logic": {
            "type": "series",
            "elements": [
              {
                "id": "r1.sub",
                "type": "math",
                "op": "SUB",
                "a": "setpoint_fuel",
                "b": "deadband_fuel",
                "dst": "lo"
              },
              {
                "id": "r1.add",
                "type": "math",
                "op": "ADD",
                "a": "setpoint_fuel",
                "b": "deadband_fuel",
                "dst": "hi"
              }
            ]
          }
        },
        {
          "id": "r2",
          "comment": "Below the band: open the fuel press solenoid",
          "logic": {
            "type": "series",
            "elements": [
              {
                "id": "r2.en",
                "type": "contact",
                "kind": "NO",
                "operand": "bb_fuel_enable",
                "comment": "loop enable"
              },
              {
                "id": "r2.lt",
                "type": "compare",
                "op": "LT",
                "a": "PT13",
                "b": "lo"
              },
              {
                "id": "r2.set",
                "type": "coil",
                "kind": "SET",
                "operand": "S2"
              }
            ]
          }
        },
        {
          "id": "r3",
          "comment": "Above the band, or loop disabled: close it",
          "logic": {
            "type": "series",
            "elements": [
              {
                "id": "r3.par",
                "type": "parallel",
                "branches": [
                  {
                    "type": "series",
                    "elements": [
                      {
                        "id": "r3.en",
                        "type": "contact",
                        "kind": "NO",
                        "operand": "bb_fuel_enable"
                      },
                      {
                        "id": "r3.gt",
                        "type": "compare",
                        "op": "GT",
                        "a": "PT13",
                        "b": "hi"
                      }
                    ]
                  },
                  {
                    "id": "r3.dis",
                    "type": "contact",
                    "kind": "NC",
                    "operand": "bb_fuel_enable",
                    "comment": "disabled -> force closed"
                  }
                ]
              },
              {
                "id": "r3.rst",
                "type": "coil",
                "kind": "RESET",
                "operand": "S2"
              }
            ]
          }
        }
      ]
    }
  },
  {
    "name": "bangbang_lox",
    "language": "ST",
    "source": "(* LOX tank bang-bang pressurisation: PT3 (LOX bang-bang board pressure) -> S1.\n   S1 opens below setpoint - deadband, closes above setpoint + deadband and holds\n   in between, which is the hysteresis band the operator actually tunes. *)\n\nPROGRAM bangbang_lox\nVAR_GLOBAL\n    (* Operator-set at runtime, not constants. These initial values are the ones\n       recorded from the stand's last pre-fire configuration (2026-09-11). *)\n    setpoint : REAL := 904.0;   (* psi *)\n    deadband : REAL := 15.0;    (* psi *)\n    bb_lox_enable : BOOL := FALSE;\nEND_VAR\n\n    IF NOT bb_lox_enable THEN\n        S1 := FALSE;\n    ELSIF PT3 < setpoint - deadband THEN\n        S1 := TRUE;\n    ELSIF PT3 > setpoint + deadband THEN\n        S1 := FALSE;\n    END_IF;   // no ELSE: inside the band S1 holds its last state\n\nEND_PROGRAM\n"
  },
  {
    "name": "gn2_purge",
    "language": "SFC",
    "source": {
      "version": 1,
      "language": "SFC",
      "name": "gn2_purge",
      "description": "PLACEHOLDER GN2 purge, transcribed from the recorded seq-custom-13 of 2026-09-11: both line purges open for 2 s, then closed.",
      "autostart": false,
      "steps": [
        {
          "name": "START",
          "id": "s.start",
          "initial": true,
          "actions": []
        },
        {
          "name": "PURGE",
          "id": "s.purge",
          "comment": "Both line purge solenoids held open for the duration of the step",
          "actions": [
            {
              "id": "a.purge",
              "qualifier": "N",
              "body": "S5 := TRUE;\nS4 := TRUE;",
              "comment": "SV-FPURGE + SV-LOXPURGE open"
            }
          ]
        },
        {
          "name": "DONE",
          "id": "s.done",
          "comment": "Pulsed on entry rather than held, so this step cannot fight an abort chain that reopens the purges later in the same scan.",
          "actions": [
            {
              "id": "a.done",
              "qualifier": "P",
              "body": "S5 := FALSE;\nS4 := FALSE;"
            }
          ]
        }
      ],
      "transitions": [
        {
          "id": "t.start",
          "from": "START",
          "to": "PURGE",
          "condition": "TRUE"
        },
        {
          "id": "t.purge",
          "from": "PURGE",
          "to": "DONE",
          "condition": "PURGE.T >= T#2s"
        }
      ]
    }
  },
  {
    "name": "hotfire",
    "language": "SFC",
    "source": {
      "version": 1,
      "language": "SFC",
      "name": "hotfire",
      "description": "Hotfire procedure supplied by the stand team (decisions.md D12, 2026-09-13): T+0.00 PB2 open, T+0.50 PB4 open, T+8.00 PB2 close, T+8.50 PB4 close, T+8.70 S4 and S5 open, T+11.70 S4 and S5 close. Every timed transition compares SYS_TIME - t_start with the stated T+, so each command lands on the first scan that starts at or after its T+ at any scan rate, instead of adding up a scan of delay per step. t_start is taken 0.000001 s early: without that margin, floating-point rounding of the subtraction fired about one command in five a scan late whenever a T+ fell on a scan boundary. The abort chain (ABORT to ABORT_DONE) is the stand's recorded abort sequence from Draco_20260911_124919.",
      "autostart": false,
      "abort_step": "ABORT",
      "vars": [
        {
          "name": "t_start",
          "type": "REAL",
          "scope": "VAR",
          "comment": "SYS_TIME at T+0.00 less 0.000001 s, seconds"
        }
      ],
      "steps": [
        {
          "name": "START",
          "id": "s.start",
          "initial": true,
          "comment": "Records T+0. A step of its own because transitions are evaluated before actions: a timed transition out of this step would read the previous run's t_start on the first scan.",
          "actions": [
            {
              "id": "a.start.t0",
              "qualifier": "P",
              "body": "t_start := SYS_TIME - 0.000001;",
              "comment": "the margin absorbs rounding in SYS_TIME - t_start and is far below any scan period"
            }
          ]
        },
        {
          "name": "OPEN_LOX_MAIN",
          "id": "s.open_lox_main",
          "comment": "T+0.00",
          "actions": [
            {
              "id": "a.pb2.open",
              "qualifier": "S",
              "name": "PB2",
              "body": "PB2 := TRUE;",
              "comment": "MV-LOX open"
            }
          ]
        },
        {
          "name": "OPEN_FUEL_MAIN",
          "id": "s.open_fuel_main",
          "comment": "T+0.50",
          "actions": [
            {
              "id": "a.pb4.open",
              "qualifier": "S",
              "name": "PB4",
              "body": "PB4 := TRUE;",
              "comment": "MV-F open"
            }
          ]
        },
        {
          "name": "CLOSE_LOX_MAIN",
          "id": "s.close_lox_main",
          "comment": "T+8.00",
          "actions": [
            {
              "id": "a.pb2.close",
              "qualifier": "R",
              "name": "PB2",
              "body": "PB2 := FALSE;",
              "comment": "MV-LOX closed"
            }
          ]
        },
        {
          "name": "CLOSE_FUEL_MAIN",
          "id": "s.close_fuel_main",
          "comment": "T+8.50",
          "actions": [
            {
              "id": "a.pb4.close",
              "qualifier": "R",
              "name": "PB4",
              "body": "PB4 := FALSE;",
              "comment": "MV-F closed"
            }
          ]
        },
        {
          "name": "OPEN_PURGES",
          "id": "s.open_purges",
          "comment": "T+8.70",
          "actions": [
            {
              "id": "a.s4.open",
              "qualifier": "S",
              "name": "S4",
              "body": "S4 := TRUE;",
              "comment": "SV-LOXPURGE open"
            },
            {
              "id": "a.s5.open",
              "qualifier": "S",
              "name": "S5",
              "body": "S5 := TRUE;",
              "comment": "SV-FPURGE open"
            }
          ]
        },
        {
          "name": "CLOSE_PURGES",
          "id": "s.close_purges",
          "comment": "T+11.70",
          "actions": [
            {
              "id": "a.s4.close",
              "qualifier": "R",
              "name": "S4",
              "body": "S4 := FALSE;",
              "comment": "SV-LOXPURGE closed"
            },
            {
              "id": "a.s5.close",
              "qualifier": "R",
              "name": "S5",
              "body": "S5 := FALSE;",
              "comment": "SV-FPURGE closed"
            }
          ]
        },
        {
          "name": "COMPLETE",
          "id": "s.complete",
          "comment": "Final step of the procedure; stays active until the sequence is started again",
          "actions": []
        },
        {
          "name": "ABORT",
          "id": "s.abort",
          "comment": "Head of the stand's recorded abort sequence. Entered by runtime.trigger_abort() from any step.",
          "actions": [
            {
              "id": "a.ab1.pb2",
              "qualifier": "R",
              "name": "PB2",
              "body": "PB2 := FALSE;",
              "comment": "MV-LOX closed"
            }
          ]
        },
        {
          "name": "ABORT_2",
          "id": "s.abort2",
          "actions": [
            {
              "id": "a.ab2.pb4",
              "qualifier": "R",
              "name": "PB4",
              "body": "PB4 := FALSE;",
              "comment": "MV-F closed"
            }
          ]
        },
        {
          "name": "ABORT_3",
          "id": "s.abort3",
          "comment": "Stop both bang-bang loops",
          "actions": [
            {
              "id": "a.ab3.s1",
              "qualifier": "R",
              "name": "S1",
              "body": "S1 := FALSE;"
            },
            {
              "id": "a.ab3.s2",
              "qualifier": "R",
              "name": "S2",
              "body": "S2 := FALSE;"
            }
          ]
        },
        {
          "name": "ABORT_4",
          "id": "s.abort4",
          "comment": "Vent both tanks and purge both lines for 5 s",
          "actions": [
            {
              "id": "a.ab4.pb1",
              "qualifier": "S",
              "name": "PB1",
              "body": "PB1 := TRUE;",
              "comment": "LOX GN2 vent open"
            },
            {
              "id": "a.ab4.pb3",
              "qualifier": "S",
              "name": "PB3",
              "body": "PB3 := TRUE;",
              "comment": "fuel GN2 vent open"
            },
            {
              "id": "a.ab4.s5",
              "qualifier": "S",
              "name": "S5",
              "body": "S5 := TRUE;",
              "comment": "fuel purge open"
            },
            {
              "id": "a.ab4.s4",
              "qualifier": "S",
              "name": "S4",
              "body": "S4 := TRUE;",
              "comment": "LOX purge open"
            }
          ]
        },
        {
          "name": "ABORT_5",
          "id": "s.abort5",
          "comment": "Purges closed; the tank vents stay open",
          "actions": [
            {
              "id": "a.ab5.s5",
              "qualifier": "R",
              "name": "S5",
              "body": "S5 := FALSE;"
            },
            {
              "id": "a.ab5.s4",
              "qualifier": "R",
              "name": "S4",
              "body": "S4 := FALSE;"
            }
          ]
        },
        {
          "name": "ABORT_DONE",
          "id": "s.abortdone",
          "comment": "End of the recorded abort sequence - stand is venting. Final step, stays active.",
          "actions": []
        }
      ],
      "transitions": [
        {
          "id": "t.start",
          "from": "START",
          "to": "OPEN_LOX_MAIN",
          "condition": "TRUE",
          "comment": "T+0.00, the sequence's first scan"
        },
        {
          "id": "t.open_fuel_main",
          "from": "OPEN_LOX_MAIN",
          "to": "OPEN_FUEL_MAIN",
          "condition": "SYS_TIME - t_start >= 0.5"
        },
        {
          "id": "t.close_lox_main",
          "from": "OPEN_FUEL_MAIN",
          "to": "CLOSE_LOX_MAIN",
          "condition": "SYS_TIME - t_start >= 8.0"
        },
        {
          "id": "t.close_fuel_main",
          "from": "CLOSE_LOX_MAIN",
          "to": "CLOSE_FUEL_MAIN",
          "condition": "SYS_TIME - t_start >= 8.5"
        },
        {
          "id": "t.open_purges",
          "from": "CLOSE_FUEL_MAIN",
          "to": "OPEN_PURGES",
          "condition": "SYS_TIME - t_start >= 8.7"
        },
        {
          "id": "t.close_purges",
          "from": "OPEN_PURGES",
          "to": "CLOSE_PURGES",
          "condition": "SYS_TIME - t_start >= 11.7"
        },
        {
          "id": "t.complete",
          "from": "CLOSE_PURGES",
          "to": "COMPLETE",
          "condition": "TRUE"
        },
        {
          "id": "t.ab1",
          "from": "ABORT",
          "to": "ABORT_2",
          "condition": "ABORT.T >= T#100ms"
        },
        {
          "id": "t.ab2",
          "from": "ABORT_2",
          "to": "ABORT_3",
          "condition": "ABORT_2.T >= T#100ms"
        },
        {
          "id": "t.ab3",
          "from": "ABORT_3",
          "to": "ABORT_4",
          "condition": "ABORT_3.T >= T#100ms"
        },
        {
          "id": "t.ab4",
          "from": "ABORT_4",
          "to": "ABORT_5",
          "condition": "ABORT_4.T >= T#5s"
        },
        {
          "id": "t.ab5",
          "from": "ABORT_5",
          "to": "ABORT_DONE",
          "condition": "TRUE"
        }
      ]
    }
  }
];
