// GENERATED by frontend/scripts/gen-tags.mjs from backend/draco_sim/tags/tags.yaml.
// Do not hand-edit; re-run the script after the tag database changes.

export interface TagInfo {
  name: string;
  kind: string;
  direction: 'in' | 'out';
  dtype: 'REAL' | 'BOOL';
  units: string;
  signal: string;
  normalState: 'NO' | 'NC' | null;
  description: string;
  reserved: boolean;
}

export const DRACO_TAGS: TagInfo[] = [
  {
    "name": "PT1",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "GN2 manifold, LOX branch, upstream of S1",
    "reserved": false
  },
  {
    "name": "PT2",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "LOX branch between RV1 and C1",
    "reserved": false
  },
  {
    "name": "PT3",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "",
    "reserved": false
  },
  {
    "name": "PT4",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "LOX tank downstream / run line near B2",
    "reserved": false
  },
  {
    "name": "PT5",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "LOX engine feed manifold",
    "reserved": false
  },
  {
    "name": "PT11",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "GN2 manifold, fuel branch, upstream of S2",
    "reserved": false
  },
  {
    "name": "PT12",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "Fuel branch downstream of S2/C3",
    "reserved": false
  },
  {
    "name": "PT13",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "",
    "reserved": false
  },
  {
    "name": "PT14",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "Fuel tank outlet upstream of B4",
    "reserved": false
  },
  {
    "name": "PT15",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "Fuel engine feed manifold",
    "reserved": false
  },
  {
    "name": "PT21",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "LOX run line upstream of venturi V1 (venturi inlet); flow pair with PT22",
    "reserved": false
  },
  {
    "name": "PT22",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "LOX run line venturi V1 throat/downstream; flow pair with PT21",
    "reserved": false
  },
  {
    "name": "PT23",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "Fuel venturi V2 inlet; flow pair with PT24",
    "reserved": false
  },
  {
    "name": "PT24",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "Fuel venturi V2 throat/downstream; flow pair with PT23",
    "reserved": false
  },
  {
    "name": "PT31",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "",
    "reserved": false
  },
  {
    "name": "PT32",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "Purge branch downstream of R1/RV5; regulated to roughly 250 psi",
    "reserved": false
  },
  {
    "name": "PT33",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "Engine feed manifold near thrust mount",
    "reserved": false
  },
  {
    "name": "PT0",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "psi",
    "signal": "pressure",
    "normalState": null,
    "description": "Combustion chamber pressure",
    "reserved": false
  },
  {
    "name": "TC1",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "degF",
    "signal": "temperature",
    "normalState": null,
    "description": "LOX tank bottom",
    "reserved": false
  },
  {
    "name": "TC2",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "degF",
    "signal": "temperature",
    "normalState": null,
    "description": "LOX tank top",
    "reserved": false
  },
  {
    "name": "TC3",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "degF",
    "signal": "temperature",
    "normalState": null,
    "description": "LOX run line, venturi inlet side (per P&ID location)",
    "reserved": false
  },
  {
    "name": "TC4",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "degF",
    "signal": "temperature",
    "normalState": null,
    "description": "LOX run line, venturi outlet side (per P&ID location)",
    "reserved": false
  },
  {
    "name": "TC5",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "degF",
    "signal": "temperature",
    "normalState": null,
    "description": "Engine feed manifold, LOX side (per P&ID location)",
    "reserved": false
  },
  {
    "name": "TC6",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "degF",
    "signal": "temperature",
    "normalState": null,
    "description": "Fuel bang-bang solenoid body temperature",
    "reserved": false
  },
  {
    "name": "TC7",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "degF",
    "signal": "temperature",
    "normalState": null,
    "description": "LOX bang-bang solenoid body temperature",
    "reserved": false
  },
  {
    "name": "TC8",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "degF",
    "signal": "temperature",
    "normalState": null,
    "description": "Chamber",
    "reserved": false
  },
  {
    "name": "LC1",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "lbf",
    "signal": "load_cell",
    "normalState": null,
    "description": "Thrust cell A",
    "reserved": false
  },
  {
    "name": "LC2",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "lbf",
    "signal": "load_cell",
    "normalState": null,
    "description": "Thrust cell B",
    "reserved": false
  },
  {
    "name": "LC3",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "lbf",
    "signal": "load_cell",
    "normalState": null,
    "description": "Thrust cell C",
    "reserved": false
  },
  {
    "name": "LC4",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "lbf",
    "signal": "load_cell",
    "normalState": null,
    "description": "LOX tank weight",
    "reserved": false
  },
  {
    "name": "LC_FUEL",
    "kind": "analog_in",
    "direction": "in",
    "dtype": "REAL",
    "units": "lbf",
    "signal": "load_cell",
    "normalState": null,
    "description": "Fuel tank weight",
    "reserved": false
  },
  {
    "name": "THRUST",
    "kind": "derived",
    "direction": "in",
    "dtype": "REAL",
    "units": "lbf",
    "signal": "derived",
    "normalState": null,
    "description": "Derived total thrust = LC1 + LC2 + LC3",
    "reserved": false
  },
  {
    "name": "S1",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "solenoid",
    "normalState": "NC",
    "description": "LOX bang-bang pressurization solenoid",
    "reserved": false
  },
  {
    "name": "S2",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "solenoid",
    "normalState": "NC",
    "description": "Fuel bang-bang pressurization solenoid",
    "reserved": false
  },
  {
    "name": "PB1",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "pneumatic_ball",
    "normalState": "NO",
    "description": "LOX tank GN2 vent",
    "reserved": false
  },
  {
    "name": "PB3",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "pneumatic_ball",
    "normalState": "NO",
    "description": "Fuel tank GN2 vent",
    "reserved": false
  },
  {
    "name": "PB2",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "pneumatic_ball",
    "normalState": "NC",
    "description": "LOX main run valve",
    "reserved": false
  },
  {
    "name": "PB4",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "pneumatic_ball",
    "normalState": "NC",
    "description": "Fuel main run valve",
    "reserved": false
  },
  {
    "name": "S5",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "solenoid",
    "normalState": "NC",
    "description": "Fuel line purge injection",
    "reserved": false
  },
  {
    "name": "S4",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "solenoid",
    "normalState": "NC",
    "description": "LOX line purge injection",
    "reserved": false
  },
  {
    "name": "PB5",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "pneumatic_ball",
    "normalState": "NC",
    "description": "LOX fill valve",
    "reserved": false
  },
  {
    "name": "S3",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "solenoid",
    "normalState": "NC",
    "description": "Muscle-bus (actuation air) vent",
    "reserved": false
  },
  {
    "name": "PB6",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "pneumatic_ball",
    "normalState": "NC",
    "description": "LOX run-line GOX vent/purge",
    "reserved": false
  },
  {
    "name": "SPARE_IGNITER",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "",
    "normalState": null,
    "description": "Reserved spare output, tentatively earmarked for an igniter circuit",
    "reserved": true
  },
  {
    "name": "SPARE_CAMERA_TRIGGER",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "",
    "normalState": null,
    "description": "Reserved spare output, tentatively earmarked for a camera trigger",
    "reserved": true
  },
  {
    "name": "SPARE_COMPRESSOR",
    "kind": "digital_out",
    "direction": "out",
    "dtype": "BOOL",
    "units": "bool",
    "signal": "",
    "normalState": null,
    "description": "Reserved spare output, tentatively earmarked for a compressor start/stop",
    "reserved": true
  }
];
